### ISSUE TITLE
Create Checklist Feature

### ISSUE THREAD

**Issue by Ofthemasses** [Ofthemasses/self-management-app#1]
## Description
My markdown files look like this for my diary:
```md
- [ ] X thing
- [ ] Y thing

---

- [ ] Z thing
```

I want two viewing modes in my app for checking these off. One that displays the first two tasks that haven't been checked off, allowing me to tap anywhere on the screen to tick off the next to-do. And a full list view, still single tap to tick them off but I have to tap the correct option.

This will replace my current system of editing my documents with Markor and the phone keyboard. The goal of this is to make doing my daily diary/to-do list as simple as possible.

## To-Do
- [x] Add more to-do's to this issue once I get an idea of what the development will be like.
- [x] Convert diary data into object
- [x] Display todo's for next to-do mode
- [x] Write to file when tapped
- [x] Auto cycle to-do's on "Next To-Do" view
- [x] Create full list view
